version: '3.6'

services:
  open_tracker_db:
    image: postgres
    restart: always    
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=op
      - POSTGRES_USER=op
      - POSTGRES_PASSWORD=${DB_PASS}
    expose:
      - 5432
    networks:
      - local

networks:
  local:
