{
 "title": "Asistencias y Votaciones - Plenos 2021-2026",
 "time": { "from": "2022-02-02T19:06:03.073Z", "to": "2022-02-02T19:16:03.073Z" },
 "panels": [
  { "title": "Asistencias", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Asistencias por Mes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT strftime('%Y-%m', fecha) as mes, count(1) total\nFROM asistencia_resultado\nGROUP BY mes;",
     "rawQueryText": "SELECT strftime('%Y-%m', fecha) as mes, count(1) total\nFROM asistencia_resultado\nGROUP BY mes;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Porcentaje de inasistencia",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT grupo_parlamentario_descripcion, 100.0 - (sum(presentes) * 100.0 / sum(total)) as porcentaje\nFROM asistencia_grupo_parlamentario\nGROUP BY grupo_parlamentario;",
     "rawQueryText": "SELECT grupo_parlamentario_descripcion, 100.0 - (sum(presentes) * 100.0 / sum(total)) as porcentaje\nFROM asistencia_grupo_parlamentario\nGROUP BY grupo_parlamentario;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Votaciones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Votaciones por Mes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT strftime('%Y-%m', fecha) as mes, count(1) total\nFROM votacion_resultado\nGROUP BY mes;",
     "rawQueryText": "SELECT strftime('%Y-%m', fecha) as mes, count(1) total\nFROM votacion_resultado\nGROUP BY mes;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Presidentes",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT presidente, count(1) total\nFROM votacion_resultado\nGROUP BY presidente;",
     "rawQueryText": "SELECT presidente, count(1) total\nFROM votacion_resultado\nGROUP BY presidente;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Resultados de Votaciones por Mes",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 29 },
   "targets": [
    {
     "queryText": "SELECT strftime('%Y-%m', fecha) as mes, sum(si >= quorum) aprobado, sum(si < quorum) desaprobado\nFROM votacion_resultado\nGROUP BY mes;",
     "rawQueryText": "SELECT strftime('%Y-%m', fecha) as mes, sum(si >= quorum) aprobado, sum(si < quorum) desaprobado\nFROM votacion_resultado\nGROUP BY mes;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}