---
version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss:8.3.3
    expose:
      - 3000
    environment:
      GF_INSTALL_PLUGINS: frser-sqlite-datasource
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      VIRTUAL_HOST: grafana.data.congreso.${HOST_DOMAIN}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: grafana.data.congreso.${HOST_DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL_DOMAIN} 
    volumes:
      - ./db:/app
      - ./grafana/:/etc/grafana/provisioning

networks:
  default:
    external:
      name: nginx-proxy
