---
version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss:8.3.3
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: frser-sqlite-datasource
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - ./db:/app
      - ./grafana/:/etc/grafana/provisioning

