name: 'Deploy grafana'

on:
  workflow_dispatch:
    branches:
    - master
    inputs:
      env_type:
        description: 'Environment type'
        required: true
        default: 'staging'

jobs:
  deploy:
    name: 'Deployment with ssh'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa # optional
        known_hosts: 'Generated-in-a-step-forward'
        if_key_exists: fail 

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: rsync over ssh
      run: rsync -av ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:congreso/open-tracker-devops/

    - name: Execute commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd congreso/open-tracker-devops/grafana
          HOST_DOMAIN=${{ secrets.HOST_DOMAIN }} EMAIL_DOMAIN=${{ secrets.EMAIL_DOMAIN }} ENV_TYPE=${{ github.event.inputs.env_type }} docker-compose up -d
