name: 'Update bills image (google-drive)'

on:
  workflow_dispatch:
    branches:
    - master

jobs:
  create:
    name: 'Create bills image'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Execute script
      run: |
        cd database/
        GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }} GLOSSARY_SHEET_ID=${{ secrets.GLOSSARY_SHEET_ID }} GOOGLE_AUTH_ENCODED=${{ secrets.GOOGLE_AUTH_ENCODED }} ./bills/create-image.sh

    - name: Upload generated image
      uses: actions/upload-artifact@v2
      with:
        name: backup_bills.sql
        path: database/backup/backup_bills.sql


  update:
    name: 'Update backup in Google Drive'
    needs: create
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Download generated image
      uses: actions/download-artifact@v2
      id: download
      with:
        name: backup_bills.sql
        path: database/backup/

    - name: Echo download path
      run: echo ${{steps.download.outputs.download-path}}

    - name: Execute script
      run: |
        cd database/
        GOOGLE_AUTH_ENCODED=${{ secrets.GOOGLE_AUTH_ENCODED }} ./bills/sync-remote.sh
