name: 'Update attendance-voting image - server (google-drive)'

on:
  workflow_run:
    workflows: ['Update attendance-voting repository (sqlite db)']
    types:
      - completed

  workflow_dispatch:
    branches:
    - master

jobs:
  create:
    name: 'Create attendance-voting image'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{ github.event_name == 'workflow_dispatch' }}

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa # optional
        known_hosts: 'Generated-in-a-step-forward'
        if_key_exists: fail 

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: rsync over ssh
      run: rsync -av ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:congreso/open-tracker-devops/

    - name: Execute commands
      uses: appleboy/ssh-action@master
      env:
        DEFAULT_ENV_TYPE: 'staging'
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd congreso/open-tracker-devops/database
          GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }} GLOSSARY_SHEET_ID=${{ secrets.GLOSSARY_SHEET_ID }} GOOGLE_AUTH_ENCODED=${{ secrets.GOOGLE_AUTH_ENCODED }} ENV_TYPE=local ./attendance-voting/create-image.sh
          GOOGLE_AUTH_ENCODED=${{ secrets.GOOGLE_AUTH_ENCODED }} ./attendance-voting/sync-remote.sh
